### PR TITLE
Added Mame 2010/0.139 roms & names to name.json / Added hataraiB core as selectable

### PR DESCRIPTION
**Pull request by voodatari**
Added Mame 2010/0.139 rom's names.

I added the names of the roms of Mame 2010 / 0.139.
However, the result is not quite correct because Mame has changed some of its roms between Mame 2003 and 2010 keeping the file name. 
For example: in Mame 2003 the rom “1943.zip” corresponds to “1943: The Battle of Midway (Euro)”, while the same rom in Mame 2010 corresponds to “1943 - The Battle of Midway (US)”. 

It would be necessary to create an individual naming system for each Mame core and FBA to avoid this problem, but in the meantime this solution is better than having only short rom names. 

Also added hatariB core as selectable. 

(sorry for merging both changes in a same pull request...github is not my thing. Feel free to change anything If it's a mistake.

### CODE REVIEW

**Comment by xonglebongle** [comment]
Got some time to look over the names and it contains many fruit machines, bios, and console system references that are not required.

**Comment by voodatari** [comment]
Combined muOS 2405.1 name.json with names from Mame 2000, Mame 2003 plus, FB Alpha 2012 Arcade, Mame 2010 and FB Neo Arcade.
Also removed mechanical, slot games, bios, systems, etc...

Note that I only combined those Mame versions since:

0.78 plus = 2003
0.139 = 2010
2000 = 0.37b5
2003 = 0.78 so, they overlap.

In addition to the combined name.json I've also included separated .json for each core just in case it could be implemented.

**Comment by xonglebongle** [comment]
I haven't forgotten about this PR just so you know! 😄

**Comment by voodatari** [comment]
Don't worry , I know there is a lot of new stuff happening in MuOS and is hard to find enough time for everything, this is just something cosmetical 😅. Thanks again for your work.

**Comment by xonglebongle** [comment]
Having a think about this and I've got a brainfart of an idea that _might_ work. Within our assign INI files we can add another global variable called `name` or `friendly` and have it point to a specific JSON file. This will work great in conjunction with the `cache` variable.

**Pull request merged**
