### PR TITLE
Add MTP device support

### PR DESCRIPTION
**Pull request by bcat**
**Note:** Requires https://github.com/MustardOS/rootfs/pull/5 with the actual MTP daemon and config file. Will also require followup frontend changes for the new muOS setting.

Adds [MTP](https://en.wikipedia.org/wiki/Media_Transfer_Protocol) USB device support using the open-source [uMTP-Responder](https://github.com/viveris/uMTP-Responder). Personally, I think I'll stick with SFTP, but this might be useful to folks on devices without wifi support, as unlike ADB, MTP is built into Windows.

I did a moderate amount of testing, and things seem to work okay. Copying 6 GB of files to the device took about 13 minutes, so roughly 7.7 MBps. I copied the same files back, compared their hashes, and got identical values, so at least there shouldn't be obvious data corruption issues. :)

As currently implemented, this is mutually exclusive with the existing ADB support. The user can choose either ADB or MTP, but not at the same time. (Theoretically, Linux `functionfs` supports [composite USB gadgets](https://docs.kernel.org/usb/functionfs.html#overview), but I couldn't get this to work, and I suspect having to choose one at a time is fine in practice. It's easy to switch between the two anyway.)

I converted the existing `android` advanced setting into a `usb_function` setting with three values:

* `none`: Handheld functions as a USB host only (USB gadget disabled)
* `adb`: Handheld functions as an ADB device (existing)
* `mtp`: Handheld functions as an MTP device (new)

Interestingly, the janky OTG implementation seems to still "work" even when a USB gadget is enabled, with e.g. a connected USB controller still working properly when the MTP daemon is running....

I haven't updated the frontend for the new preference (both because I don't know how and because I didn't have more time to hack on this now), but for the moment, you can test out the new functionality by running the following commands:

```shell
echo {none|adb|mtp} >/run/muos/global/settings/advanced/usb_function && /opt/muos/script/system/usb.sh
```

### CODE REVIEW

**Comment by xonglebongle** [comment]
Are you able to resolve conflict from previous merged PR, thanks! :smile:

**Comment by bcat** [comment]
> Are you able to resolve conflict from previous merged PR, thanks! 😄

Sure, in progress! (I've got a few other small tweaks I wanted to make anyway.)

**Comment by bcat** [comment]
Done, and rebased!

**Comment by bcat** [comment]
BTW, if you have time, do you mind updating the pref in the settings UI? At some point I really should learn enough LVGL (and Squareline Studio?) to do basic things like that, but I haven't yet, and I figure it's probably much quicker for you to do than me. 😃

**Pull request merged**
